### ISSUE TITLE
External Tools broken

### ISSUE THREAD

**Issue by tmugrage** [kmscode/mRemote3G#10]
If you add a new external tool, you get an error and the application crashes. With the External Tools panel open, you can hit the New button. You can change the display name in the External Tool Properties below. You can set the filename (path) to the executable. But once you click on anything after that point, it crashes. (mremote log below)

Notes:
* This was test with an external tool with and without long path name with the same results
* With the same win10 laptop, this issue did not exist on ver. 1.84
* none of the xml files in my install were ported over from 1.84 to 1.90 and onward

**mremote3g.log snippet**
2016-01-14 10:28:13,166 [1] INFO - mRemote3G 1.92.5851.23374 Portable Edition starting.
2016-01-14 10:28:13,172 [1] INFO - Command Line: C:\applications\mRemote3G\mRemote3G.exe
2016-01-14 10:28:14,248 [1] INFO - Microsoft Windows 10 Enterprise 64-bit
2016-01-14 10:28:14,249 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2016-01-14 10:28:14,250 [1] INFO - System Culture: en-US/English (United States)
2016-01-14 10:28:15,867 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
System.ArgumentException: The directory name sessions is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at mRemoteNG.Config.Putty.XmingProvider.StartWatcher()

**Comment by kmscode** [comment]
That's a different exception (which doesn't appear to cause any problems). This is appears to be the exception that causes the reported problem:
2016-01-14 16:31:34,012 [1] ERROR- ExternalApp.Start() failed.
System.InvalidOperationException: FileName cannot be blank.
   at mRemoteNG.Tools.ExternalTool.Start(Info startConnectionInfo)

I was able to reproduce this once in a "release" build, but of course everything worked as expected (received the exception in the notifications panel) when debugging in Visual Studio. 

Will continue to review...

**Comment by kmscode** [comment]
Should be fixed with b2488494281e2da466c623750c766ad7712f5326

Hope to have a release that includes this by early next week (at the latest).

**Comment by kmscode** [comment]
Version 1.93 can be found here: https://github.com/kmscode/mRemote3G/releases/tag/1.93

**Comment by damian-kaczkowski** [comment]
Still not fixed. 1.84 works. 1.93 does not. Tested on windows 7 pro and windown 10 pro.
```
2016-01-24 03:52:19,652 [1] INFO - mRemote3G 1.93.5864.31827 Portable Edition starting.
2016-01-24 03:52:19,652 [1] INFO - Command Line: C:\mRemote3G-1.93\mRemote3G.exe
2016-01-24 03:52:19,855 [1] INFO - Microsoft Windows 7 Professional Service Pack 1 64-bit
2016-01-24 03:52:19,855 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2016-01-24 03:52:19,855 [1] INFO - System Culture: en-US/English (United States)
2016-01-24 03:52:20,666 [1] WARN - Couldn't create backup of connections file!
System.IO.FileNotFoundException: Could not find file 'C:\mRemote3G-1.93\confCons.xml'.
File name: 'C:\mRemote3G-1.93\confCons.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at mRemoteNG.App.Runtime.CreateBackupFile(String fileName)
2016-01-24 03:52:20,666 [1] INFO - Connections file "C:\mRemote3G-1.93\confCons.xml" could not be loaded!
Starting with new connections file.
System.IO.FileNotFoundException: Could not find file 'C:\mRemote3G-1.93\confCons.xml'.
File name: 'C:\mRemote3G-1.93\confCons.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at mRemoteNG.App.Runtime.CreateBackupFile(String fileName)
   at mRemoteNG.App.Runtime.LoadConnections(Boolean withDialog, Boolean update)
2016-01-24 03:52:20,791 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
System.ArgumentException: The directory name sessions is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at mRemoteNG.Config.Putty.XmingProvider.StartWatcher()
```

**Comment by kmscode** [comment]
@damiankaczkowski those exceptions have nothing do to with external tools.

The first 2 are complaining that it can't load your connections file. Try coping a known good confCons.xml into the 1.9.3 directory and see if that takes care of the problem. Also, validate permissions. If you had to elevate to administrator to copy the mremote3g dir to the C: drive, then it's possible that it's inheriting the more restricted permissions from C:. Make sure your user owns that dir and has read/write access to it directly (without any additional UAC prompts).

The last one has to do with putty sessions. It happens in my instances also. It's not known to cause any problems that I'm aware of. I haven't traced it down though.

**Comment by damiankaczkowski** [comment]
@kmscode I just paste the full log. This is the full log since first launch of the application after extracting from zip. During this first start application warns about missing confCons.xml  and just creates it and no longer warn about it. I just wanted to leave those logs to show that this is the first run of the app.

Regarding C: path. I just unpack the application directly to C: To make the path shorter. It doesn't matter if the path is C, D, or whatever cause I was testing on local admin account.

The problem is exactly the same as OP reported. mremote3g works until you click on the interface after adding the ext app. If you add ext app with wrong path, then mremote3g won't crash. It crashes only if the ext app path is correct.

Movie here:
https://www.dropbox.com/s/vk4ih6qjm37pjh7/VID_20160125_173902.3gp?dl=0

Error:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mRemote3G.exe
  Application Version:	1.93.5864.31827
  Application Timestamp:	56a15e77
  Fault Module Name:	clr.dll
  Fault Module Version:	4.6.1055.0
  Fault Module Timestamp:	563c0f73
  Exception Code:	c0000005
  Exception Offset:	00013693
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1045
  Additional Information 1:	59ec
  Additional Information 2:	59ec722848189ea3e98798350357bee0
  Additional Information 3:	46ca
  Additional Information 4:	46caad7b34187914e553b32a1233c835

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by kmscode** [comment]
@damiankaczkowski I was able to reproduce this after watching you video. I'll look into this further.

**Comment by kmscode** [comment]
@tmugrage @damiankaczkowski Give [1.94.1](https://github.com/kmscode/mRemote3G/releases/tag/1.94.1) a whirl. Let me know if you're still having problems.

**Comment by damiankaczkowski** [comment]
I confirm that this bug is fixed in 1.94.1. You may now add external tool without a crash. Thank you for the fix.

**Comment by tmugrage** [comment]
I confirm its fixed here also. External tools are functional again. Thank you for your persistence on this one.
